version: '3.5'

services:
  api:
    build: .
    container_name: java-spring-service
    image: quay.io/paulpop/java-spring-service
    ports:
      - "8080:8080"
    networks:
      - overlay
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}changeme
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}changeme
      - MYSQL_DATABASE=${MYSQL_DATABASE}db_example
    ports:
      - "3306:3306"
networks:
  overlay:
