version: '3.5'

services:
  api:
    build: .
    container_name: java-spring-service
    image: quay.io/paulpop/java-spring-service
    ports:
      - "8080:8080"
    networks:
      - overlay
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}

networks:
  overlay:
