version: '3.5'

services:
  api:
    build: .
    container_name: java-spring-service
    ports:
      - "8080:8080"
    networks:
      - overlay
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - ./config/:/config
      - ./target/java-spring-service.jar ./
    command: ['sh', '-c', 'java -Djava.security.egd=file:/dev/./urandom -jar -DADMIN_PASSWORD=$ADMIN_PASSWORD ./java-spring-service.jar --spring.profiles.active=$ENVIRONMENT']
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - "3306:3306"
networks:
  overlay:
