version: '3.5'

services:
  api:
    build: .
    container_name: java-spring-service
    ports:
      - "8080:8080"
    networks:
      - overlay
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - AWS_ACCESS_ID=${AWS_ACCESS_ID}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
networks:
  overlay:
