spring:
  application:
    name: java-spring-service
  mvc:
    throw-exception-if-no-handler-found: false
  resources:
    add-mappings: true
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

logging:
  level:
    root: INFO
  accesslog:
    pattern: '%h %l %u [%t] "%r" %s %b "Referer: %i{Referer}" "X-Forwarded-For: %i{X-Forwarded-For}" "User-Agent: %i{User-Agent}"'

management:
   security:
     enabled: true

### To be overridden - these are only used for local ###
security:
   basic:
     enabled: false
   user:
     name: admin
     password: admin